---
- hosts: ubuntu
  tasks:
  - name: Part One Disable IPV6 Linux
    lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1" state=present
    notify: 
    - Reload IPV6 Sysctl

  - name: Part Two Disable IPV6
    lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"  state=present
    notify:
      - Reload IPV6 Sysctl

  - name: Part Three Disable IPV6
    lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"  state=present
    notify:
      - Reload IPV6 Sysctl


  handlers:
    - name: Reload IPV6 Sysctl
      command: /sbin/sysctl -p



