---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Run apt-get update and apt-get upgrade without reboot
    apt: update_cache=yes
  - name: Runs apt-get upgrade remember to reboot manually
    apt: upgrade=dist

